import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import ArjunNoBackground from "../arjunTransparent.png";
import ArjunStandingNoBackground from "arjunStandingTransparent.png";
import { useCallback } from "react";
import Particles from "react-tsparticles";
import { loadSeaAnemonePreset } from "tsparticles-preset-sea-anemone";
import { loadFull } from "tsparticles";

export default function Home() {
  const particlesInit = useCallback(async (engine) => {
    console.log(engine);

    await loadSeaAnemonePreset(engine);
  }, []);
  const particlesLoaded = useCallback(async (container) => {
    await console.log(container);
  }, []);
  return (
    <>
      <Head>
        <title>Arjun Rawal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
          <h1 className={styles.name}>
            Arjun Rawal
          </h1>
          <Image
            src={ArjunNoBackground}
            alt="Arjun Rawal"
            className={styles.avatar}
          />
        </div>
        <Particles
          id="tsparticles"
          init={particlesInit}
          loaded={particlesLoaded}
          options={{
            preset: "seaAnemone",

          }}
        />
      </main>
    </>
  );
}
